[package]
name = "api-test"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
log = "0.4.22"
qdrant-client = "1.12.1"
tokio = { version = "1.42.0", features=["full"] }
tokio-test = "0.4.4"

