apiVersion: v1
kind: ServiceAccount
metadata:
  name: support-bundle-sa
  namespace: qdrant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: support-bundle-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: support-bundle-rb
subjects:
  - kind: ServiceAccount
    name: support-bundle-sa
    namespace: qdrant
roleRef:
  kind: ClusterRole
  name: support-bundle-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: support-bundle-job
  namespace: qdrant
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: support-bundle
    spec:
      restartPolicy: Never
      serviceAccountName: support-bundle-sa
      containers:
        - name: bundle
          image: zettertty/qdrant-support-bundle:v0.4
          imagePullPolicy: IfNotPresent